# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\qt-learning\ui\windows\reparent\forms\subFrame.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(322, 138)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.subFrameLayout = QtWidgets.QHBoxLayout()
        self.subFrameLayout.setObjectName("subFrameLayout")
        self.subFrameLabel = QtWidgets.QLabel(Form)
        self.subFrameLabel.setObjectName("subFrameLabel")
        self.subFrameLayout.addWidget(self.subFrameLabel)
        self.subFrameComboBox = QtWidgets.QComboBox(Form)
        self.subFrameComboBox.setObjectName("subFrameComboBox")
        self.subFrameLayout.addWidget(self.subFrameComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.subFrameLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.subFrameLayout)
        self.subFrameOptionsLayout = QtWidgets.QFormLayout()
        self.subFrameOptionsLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.subFrameOptionsLayout.setObjectName("subFrameOptionsLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setFrame(True)
        self.doubleSpinBox.setReadOnly(False)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setSuffix("")
        self.doubleSpinBox.setDecimals(2)
        self.doubleSpinBox.setMaximum(360.0)
        self.doubleSpinBox.setProperty("value", 180.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout.addWidget(self.doubleSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.subFrameOptionsLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.angleLabel = QtWidgets.QLabel(Form)
        self.angleLabel.setObjectName("angleLabel")
        self.subFrameOptionsLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.angleLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.samplesSpinBox = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.samplesSpinBox.sizePolicy().hasHeightForWidth())
        self.samplesSpinBox.setSizePolicy(sizePolicy)
        self.samplesSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.samplesSpinBox.setMinimum(1)
        self.samplesSpinBox.setMaximum(33)
        self.samplesSpinBox.setSingleStep(2)
        self.samplesSpinBox.setObjectName("samplesSpinBox")
        self.horizontalLayout_2.addWidget(self.samplesSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.subFrameOptionsLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.samplesLabel = QtWidgets.QLabel(Form)
        self.samplesLabel.setObjectName("samplesLabel")
        self.subFrameOptionsLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.samplesLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMaximum(1.0)
        self.doubleSpinBox_2.setProperty("value", 0.5)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.subFrameOptionsLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.durationLabel = QtWidgets.QLabel(Form)
        self.durationLabel.setObjectName("durationLabel")
        self.subFrameOptionsLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.durationLabel)
        self.verticalLayout.addLayout(self.subFrameOptionsLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.subFrameLabel.setText(_translate("Form", "Sub-Frame"))
        self.angleLabel.setText(_translate("Form", "Angle"))
        self.samplesLabel.setText(_translate("Form", "Samples"))
        self.durationLabel.setText(_translate("Form", "Duration"))

