# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/davidc/dev/qt-learning/ui/windows/assetBrowser/assetBrowser.ui'
#
# Created: Wed Oct 18 20:52:41 2017
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(838, 589)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchBarLayout = QtGui.QHBoxLayout()
        self.searchBarLayout.setObjectName("searchBarLayout")
        self.verticalLayout.addLayout(self.searchBarLayout)
        self.searchCustomFrame = QtGui.QFrame(Form)
        self.searchCustomFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.searchCustomFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.searchCustomFrame.setObjectName("searchCustomFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.searchCustomFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchCustomLayout = QtGui.QVBoxLayout()
        self.searchCustomLayout.setObjectName("searchCustomLayout")
        self.verticalLayout_3.addLayout(self.searchCustomLayout)
        self.verticalLayout.addWidget(self.searchCustomFrame)
        self.assetListViewLayout = QtGui.QHBoxLayout()
        self.assetListViewLayout.setObjectName("assetListViewLayout")
        self.verticalLayout.addLayout(self.assetListViewLayout)
        self.assetDetailsLayout = QtGui.QHBoxLayout()
        self.assetDetailsLayout.setObjectName("assetDetailsLayout")
        self.assetActionsLayout = QtGui.QVBoxLayout()
        self.assetActionsLayout.setObjectName("assetActionsLayout")
        self.assetDetailsLayout.addLayout(self.assetActionsLayout)
        self.assetInfoViewLayout = QtGui.QVBoxLayout()
        self.assetInfoViewLayout.setObjectName("assetInfoViewLayout")
        self.assetDetailsLayout.addLayout(self.assetInfoViewLayout)
        self.assetCartLayout = QtGui.QVBoxLayout()
        self.assetCartLayout.setObjectName("assetCartLayout")
        self.assetDetailsLayout.addLayout(self.assetCartLayout)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.shotViewTab = QtGui.QWidget()
        self.shotViewTab.setEnabled(True)
        self.shotViewTab.setObjectName("shotViewTab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.shotViewTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.shotViewLayout = QtGui.QVBoxLayout()
        self.shotViewLayout.setObjectName("shotViewLayout")
        self.verticalLayout_6.addLayout(self.shotViewLayout)
        self.tabWidget.addTab(self.shotViewTab, "")
        self.assetIncomingTab = QtGui.QWidget()
        self.assetIncomingTab.setObjectName("assetIncomingTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.assetIncomingTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.assetIncomingViewLayout = QtGui.QVBoxLayout()
        self.assetIncomingViewLayout.setObjectName("assetIncomingViewLayout")
        self.verticalLayout_4.addLayout(self.assetIncomingViewLayout)
        self.tabWidget.addTab(self.assetIncomingTab, "")
        self.assetOutgoingTab = QtGui.QWidget()
        self.assetOutgoingTab.setObjectName("assetOutgoingTab")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.assetOutgoingTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.assetOutgoingViewLayout = QtGui.QVBoxLayout()
        self.assetOutgoingViewLayout.setObjectName("assetOutgoingViewLayout")
        self.verticalLayout_9.addLayout(self.assetOutgoingViewLayout)
        self.tabWidget.addTab(self.assetOutgoingTab, "")
        self.tagViewTab = QtGui.QWidget()
        self.tagViewTab.setObjectName("tagViewTab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tagViewTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tagViewLayout = QtGui.QVBoxLayout()
        self.tagViewLayout.setObjectName("tagViewLayout")
        self.verticalLayout_5.addLayout(self.tagViewLayout)
        self.tabWidget.addTab(self.tagViewTab, "")
        self.keyvalueTab = QtGui.QWidget()
        self.keyvalueTab.setObjectName("keyvalueTab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.keyvalueTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.keyvalueViewLayout = QtGui.QVBoxLayout()
        self.keyvalueViewLayout.setObjectName("keyvalueViewLayout")
        self.verticalLayout_7.addLayout(self.keyvalueViewLayout)
        self.tabWidget.addTab(self.keyvalueTab, "")
        self.assetDetailsLayout.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.assetDetailsLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shotViewTab), QtGui.QApplication.translate("Form", "Linked Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.assetIncomingTab), QtGui.QApplication.translate("Form", "Incoming Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.assetOutgoingTab), QtGui.QApplication.translate("Form", "Outgoing Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tagViewTab), QtGui.QApplication.translate("Form", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.keyvalueTab), QtGui.QApplication.translate("Form", "Key Values", None, QtGui.QApplication.UnicodeUTF8))

