# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\qt-learning\ui\windows\assetBrowser\assetBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(457, 251)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.assetSearchLayout = QtWidgets.QVBoxLayout()
        self.assetSearchLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.assetSearchLayout.setSpacing(3)
        self.assetSearchLayout.setObjectName("assetSearchLayout")
        self.searchBarLayout = QtWidgets.QHBoxLayout()
        self.searchBarLayout.setSpacing(3)
        self.searchBarLayout.setObjectName("searchBarLayout")
        self.assetSearchLayout.addLayout(self.searchBarLayout)
        self.searchCustomFrame = QtWidgets.QFrame(Form)
        self.searchCustomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchCustomFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.searchCustomFrame.setObjectName("searchCustomFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.searchCustomFrame)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchCustomLayout = QtWidgets.QVBoxLayout()
        self.searchCustomLayout.setSpacing(3)
        self.searchCustomLayout.setObjectName("searchCustomLayout")
        self.verticalLayout_3.addLayout(self.searchCustomLayout)
        self.assetSearchLayout.addWidget(self.searchCustomFrame)
        self.assetListViewLayout = QtWidgets.QHBoxLayout()
        self.assetListViewLayout.setSpacing(3)
        self.assetListViewLayout.setObjectName("assetListViewLayout")
        self.assetSearchLayout.addLayout(self.assetListViewLayout)
        self.assetInfoLayout_2 = QtWidgets.QHBoxLayout()
        self.assetInfoLayout_2.setContentsMargins(0, 0, 0, 0)
        self.assetInfoLayout_2.setSpacing(3)
        self.assetInfoLayout_2.setObjectName("assetInfoLayout_2")
        self.assetInfoViewLayout = QtWidgets.QVBoxLayout()
        self.assetInfoViewLayout.setSpacing(3)
        self.assetInfoViewLayout.setObjectName("assetInfoViewLayout")
        self.assetInfoLayout_2.addLayout(self.assetInfoViewLayout)
        self.tagViewLayout = QtWidgets.QVBoxLayout()
        self.tagViewLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.tagViewLayout.setSpacing(3)
        self.tagViewLayout.setObjectName("tagViewLayout")
        self.assetInfoLayout_2.addLayout(self.tagViewLayout)
        self.assetSearchLayout.addLayout(self.assetInfoLayout_2)
        self.horizontalLayout.addLayout(self.assetSearchLayout)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.assetDetailsLayout = QtWidgets.QVBoxLayout()
        self.assetDetailsLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.assetDetailsLayout.setContentsMargins(0, 0, 0, 0)
        self.assetDetailsLayout.setSpacing(3)
        self.assetDetailsLayout.setObjectName("assetDetailsLayout")
        self.shotViewLayout = QtWidgets.QVBoxLayout()
        self.shotViewLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.shotViewLayout.setSpacing(3)
        self.shotViewLayout.setObjectName("shotViewLayout")
        self.assetDetailsLayout.addLayout(self.shotViewLayout)
        self.assetDependenciesViewLayout = QtWidgets.QVBoxLayout()
        self.assetDependenciesViewLayout.setObjectName("assetDependenciesViewLayout")
        self.assetDetailsLayout.addLayout(self.assetDependenciesViewLayout)
        self.keyvalueViewLayout = QtWidgets.QVBoxLayout()
        self.keyvalueViewLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.keyvalueViewLayout.setSpacing(3)
        self.keyvalueViewLayout.setObjectName("keyvalueViewLayout")
        self.assetDetailsLayout.addLayout(self.keyvalueViewLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.assetDetailsLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.assetDetailsLayout)
        self.assetCartGroupLayout = QtWidgets.QVBoxLayout()
        self.assetCartGroupLayout.setSpacing(3)
        self.assetCartGroupLayout.setObjectName("assetCartGroupLayout")
        self.assetCartLayout = QtWidgets.QVBoxLayout()
        self.assetCartLayout.setSpacing(3)
        self.assetCartLayout.setObjectName("assetCartLayout")
        self.assetCartGroupLayout.addLayout(self.assetCartLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.assetCartGroupLayout.addWidget(self.line)
        self.assetActionsLayout = QtWidgets.QVBoxLayout()
        self.assetActionsLayout.setSpacing(3)
        self.assetActionsLayout.setObjectName("assetActionsLayout")
        self.assetCartGroupLayout.addLayout(self.assetActionsLayout)
        self.horizontalLayout.addLayout(self.assetCartGroupLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

