# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/data/Public/qt-learning/ui/windows/assetBrowser/assetBrowser.ui'
#
# Created: Tue Nov 14 19:29:10 2017
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(457, 251)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.assetSearchLayout = QtGui.QVBoxLayout()
        self.assetSearchLayout.setSpacing(3)
        self.assetSearchLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.assetSearchLayout.setObjectName("assetSearchLayout")
        self.searchBarLayout = QtGui.QHBoxLayout()
        self.searchBarLayout.setSpacing(3)
        self.searchBarLayout.setObjectName("searchBarLayout")
        self.assetSearchLayout.addLayout(self.searchBarLayout)
        self.searchCustomFrame = QtGui.QFrame(Form)
        self.searchCustomFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.searchCustomFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.searchCustomFrame.setObjectName("searchCustomFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.searchCustomFrame)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchCustomLayout = QtGui.QVBoxLayout()
        self.searchCustomLayout.setSpacing(3)
        self.searchCustomLayout.setObjectName("searchCustomLayout")
        self.verticalLayout_3.addLayout(self.searchCustomLayout)
        self.assetSearchLayout.addWidget(self.searchCustomFrame)
        self.assetListViewLayout = QtGui.QHBoxLayout()
        self.assetListViewLayout.setSpacing(3)
        self.assetListViewLayout.setObjectName("assetListViewLayout")
        self.assetSearchLayout.addLayout(self.assetListViewLayout)
        self.assetInfoLayout_2 = QtGui.QHBoxLayout()
        self.assetInfoLayout_2.setSpacing(3)
        self.assetInfoLayout_2.setMargin(0)
        self.assetInfoLayout_2.setObjectName("assetInfoLayout_2")
        self.assetInfoViewLayout = QtGui.QVBoxLayout()
        self.assetInfoViewLayout.setSpacing(3)
        self.assetInfoViewLayout.setObjectName("assetInfoViewLayout")
        self.assetInfoLayout_2.addLayout(self.assetInfoViewLayout)
        self.tagViewLayout = QtGui.QVBoxLayout()
        self.tagViewLayout.setSpacing(3)
        self.tagViewLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.tagViewLayout.setObjectName("tagViewLayout")
        self.assetInfoLayout_2.addLayout(self.tagViewLayout)
        self.assetSearchLayout.addLayout(self.assetInfoLayout_2)
        self.horizontalLayout.addLayout(self.assetSearchLayout)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.assetDetailsLayout = QtGui.QVBoxLayout()
        self.assetDetailsLayout.setSpacing(3)
        self.assetDetailsLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.assetDetailsLayout.setMargin(0)
        self.assetDetailsLayout.setObjectName("assetDetailsLayout")
        self.shotViewLayout = QtGui.QVBoxLayout()
        self.shotViewLayout.setSpacing(3)
        self.shotViewLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.shotViewLayout.setObjectName("shotViewLayout")
        self.assetDetailsLayout.addLayout(self.shotViewLayout)
        self.assetDependenciesViewLayout = QtGui.QVBoxLayout()
        self.assetDependenciesViewLayout.setObjectName("assetDependenciesViewLayout")
        self.assetDetailsLayout.addLayout(self.assetDependenciesViewLayout)
        self.keyvalueViewLayout = QtGui.QVBoxLayout()
        self.keyvalueViewLayout.setSpacing(3)
        self.keyvalueViewLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.keyvalueViewLayout.setObjectName("keyvalueViewLayout")
        self.assetDetailsLayout.addLayout(self.keyvalueViewLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.assetDetailsLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.assetDetailsLayout)
        self.assetCartGroupLayout = QtGui.QVBoxLayout()
        self.assetCartGroupLayout.setSpacing(3)
        self.assetCartGroupLayout.setObjectName("assetCartGroupLayout")
        self.assetCartLayout = QtGui.QVBoxLayout()
        self.assetCartLayout.setSpacing(3)
        self.assetCartLayout.setObjectName("assetCartLayout")
        self.assetCartGroupLayout.addLayout(self.assetCartLayout)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.assetCartGroupLayout.addWidget(self.line)
        self.assetActionsLayout = QtGui.QVBoxLayout()
        self.assetActionsLayout.setSpacing(3)
        self.assetActionsLayout.setObjectName("assetActionsLayout")
        self.assetCartGroupLayout.addLayout(self.assetActionsLayout)
        self.horizontalLayout.addLayout(self.assetCartGroupLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))

