# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\qt-learning\ui\windows\assetBrowser\forms\assetListView.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(947, 330)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.listWidget_12 = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_12.sizePolicy().hasHeightForWidth())
        self.listWidget_12.setSizePolicy(sizePolicy)
        self.listWidget_12.setMinimumSize(QtCore.QSize(80, 0))
        self.listWidget_12.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setItalic(False)
        self.listWidget_12.setFont(font)
        self.listWidget_12.setObjectName("listWidget_12")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_12.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_12.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_12.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_12.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_12.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_12.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_12.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_12.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_12.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget_12)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Row1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Row2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Row3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "Row4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "Row5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Thumbnail"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Path"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Latest"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Approved"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Users"))
        __sortingEnabled = self.listWidget_12.isSortingEnabled()
        self.listWidget_12.setSortingEnabled(False)
        item = self.listWidget_12.item(0)
        item.setText(_translate("Form", "<none>"))
        item = self.listWidget_12.item(1)
        item.setText(_translate("Form", "v001"))
        item = self.listWidget_12.item(2)
        item.setText(_translate("Form", "v002 (deleted)"))
        item = self.listWidget_12.item(3)
        item.setText(_translate("Form", "v003 (approved)"))
        item = self.listWidget_12.item(4)
        item.setText(_translate("Form", "v004 (ready)"))
        item = self.listWidget_12.item(5)
        item.setText(_translate("Form", "v005"))
        item = self.listWidget_12.item(6)
        item.setText(_translate("Form", "v006 (latest)"))
        item = self.listWidget_12.item(7)
        item.setText(_translate("Form", "<latest>"))
        item = self.listWidget_12.item(8)
        item.setText(_translate("Form", "<approved>"))
        self.listWidget_12.setSortingEnabled(__sortingEnabled)

