# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/davidc/dev/qt-learning/ui/windows/assetBrowser/forms/assetListView.ui'
#
# Created: Wed Oct 18 20:52:41 2017
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(947, 330)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtGui.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.listWidget_12 = QtGui.QListWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_12.sizePolicy().hasHeightForWidth())
        self.listWidget_12.setSizePolicy(sizePolicy)
        self.listWidget_12.setMinimumSize(QtCore.QSize(80, 0))
        self.listWidget_12.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setItalic(False)
        self.listWidget_12.setFont(font)
        self.listWidget_12.setObjectName("listWidget_12")
        QtGui.QListWidgetItem(self.listWidget_12)
        QtGui.QListWidgetItem(self.listWidget_12)
        QtGui.QListWidgetItem(self.listWidget_12)
        QtGui.QListWidgetItem(self.listWidget_12)
        QtGui.QListWidgetItem(self.listWidget_12)
        QtGui.QListWidgetItem(self.listWidget_12)
        QtGui.QListWidgetItem(self.listWidget_12)
        QtGui.QListWidgetItem(self.listWidget_12)
        QtGui.QListWidgetItem(self.listWidget_12)
        self.horizontalLayout.addWidget(self.listWidget_12)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Row1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Row2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Row3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Row4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Row5", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Thumbnail", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Latest", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Approved", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "Users", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget_12.isSortingEnabled()
        self.listWidget_12.setSortingEnabled(False)
        self.listWidget_12.item(0).setText(QtGui.QApplication.translate("Form", "<none>", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_12.item(1).setText(QtGui.QApplication.translate("Form", "v001", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_12.item(2).setText(QtGui.QApplication.translate("Form", "v002 (deleted)", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_12.item(3).setText(QtGui.QApplication.translate("Form", "v003 (approved)", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_12.item(4).setText(QtGui.QApplication.translate("Form", "v004 (ready)", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_12.item(5).setText(QtGui.QApplication.translate("Form", "v005", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_12.item(6).setText(QtGui.QApplication.translate("Form", "v006 (latest)", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_12.item(7).setText(QtGui.QApplication.translate("Form", "<latest>", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_12.item(8).setText(QtGui.QApplication.translate("Form", "<approved>", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_12.setSortingEnabled(__sortingEnabled)

