# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/data/Public/qt-learning/ui/windows/assetBrowser/forms/assetListView.ui'
#
# Created: Tue Nov 14 19:29:10 2017
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(947, 327)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.assetTableLayout = QtGui.QVBoxLayout()
        self.assetTableLayout.setSpacing(0)
        self.assetTableLayout.setObjectName("assetTableLayout")
        self.assetTableWidget = QtGui.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.assetTableWidget.setFont(font)
        self.assetTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.assetTableWidget.setObjectName("assetTableWidget")
        self.assetTableWidget.setColumnCount(7)
        self.assetTableWidget.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.assetTableWidget.setHorizontalHeaderItem(6, item)
        self.assetTableLayout.addWidget(self.assetTableWidget)
        self.assetListWidget = QtGui.QListWidget(Form)
        self.assetListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.assetListWidget.setMovement(QtGui.QListView.Static)
        self.assetListWidget.setFlow(QtGui.QListView.LeftToRight)
        self.assetListWidget.setProperty("isWrapping", True)
        self.assetListWidget.setResizeMode(QtGui.QListView.Adjust)
        self.assetListWidget.setLayoutMode(QtGui.QListView.Batched)
        self.assetListWidget.setGridSize(QtCore.QSize(64, 64))
        self.assetListWidget.setViewMode(QtGui.QListView.IconMode)
        self.assetListWidget.setModelColumn(0)
        self.assetListWidget.setUniformItemSizes(True)
        self.assetListWidget.setBatchSize(1000)
        self.assetListWidget.setWordWrap(False)
        self.assetListWidget.setSelectionRectVisible(True)
        self.assetListWidget.setObjectName("assetListWidget")
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        QtGui.QListWidgetItem(self.assetListWidget)
        self.assetTableLayout.addWidget(self.assetListWidget)
        self.horizontalLayout.addLayout(self.assetTableLayout)
        self.versionListLayout = QtGui.QVBoxLayout()
        self.versionListLayout.setSpacing(3)
        self.versionListLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.versionListLayout.setObjectName("versionListLayout")
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.versionListLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtGui.QComboBox(Form)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.versionListLayout.addWidget(self.comboBox_2)
        self.versionListWidget = QtGui.QListWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionListWidget.sizePolicy().hasHeightForWidth())
        self.versionListWidget.setSizePolicy(sizePolicy)
        self.versionListWidget.setMinimumSize(QtCore.QSize(80, 0))
        self.versionListWidget.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setItalic(False)
        self.versionListWidget.setFont(font)
        self.versionListWidget.setObjectName("versionListWidget")
        QtGui.QListWidgetItem(self.versionListWidget)
        QtGui.QListWidgetItem(self.versionListWidget)
        QtGui.QListWidgetItem(self.versionListWidget)
        QtGui.QListWidgetItem(self.versionListWidget)
        QtGui.QListWidgetItem(self.versionListWidget)
        QtGui.QListWidgetItem(self.versionListWidget)
        QtGui.QListWidgetItem(self.versionListWidget)
        QtGui.QListWidgetItem(self.versionListWidget)
        QtGui.QListWidgetItem(self.versionListWidget)
        self.versionListLayout.addWidget(self.versionListWidget)
        self.horizontalLayout.addLayout(self.versionListLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Row1", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Row2", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Row3", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Row4", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Row5", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Thumbnail", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Latest", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Approved", None, QtGui.QApplication.UnicodeUTF8))
        self.assetTableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "Users", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.assetListWidget.isSortingEnabled()
        self.assetListWidget.setSortingEnabled(False)
        self.assetListWidget.item(0).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(1).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(2).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(3).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(4).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(5).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(6).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(7).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(8).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(9).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(10).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(11).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(12).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(13).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(14).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(15).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.item(16).setText(QtGui.QApplication.translate("Form", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.assetListWidget.setSortingEnabled(__sortingEnabled)
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Form", "Approved", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Form", "Latest", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Form", "Deleted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Form", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("Form", "<all departments>", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("Form", "Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("Form", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(3, QtGui.QApplication.translate("Form", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(4, QtGui.QApplication.translate("Form", "Light", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(5, QtGui.QApplication.translate("Form", "FX", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(6, QtGui.QApplication.translate("Form", "Rigging", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(7, QtGui.QApplication.translate("Form", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(8, QtGui.QApplication.translate("Form", "LookDev", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.versionListWidget.isSortingEnabled()
        self.versionListWidget.setSortingEnabled(False)
        self.versionListWidget.item(0).setText(QtGui.QApplication.translate("Form", "<none>", None, QtGui.QApplication.UnicodeUTF8))
        self.versionListWidget.item(1).setText(QtGui.QApplication.translate("Form", "v001", None, QtGui.QApplication.UnicodeUTF8))
        self.versionListWidget.item(2).setText(QtGui.QApplication.translate("Form", "v002 (deleted)", None, QtGui.QApplication.UnicodeUTF8))
        self.versionListWidget.item(3).setText(QtGui.QApplication.translate("Form", "v003 (approved)", None, QtGui.QApplication.UnicodeUTF8))
        self.versionListWidget.item(4).setText(QtGui.QApplication.translate("Form", "v004 (ready)", None, QtGui.QApplication.UnicodeUTF8))
        self.versionListWidget.item(5).setText(QtGui.QApplication.translate("Form", "v005", None, QtGui.QApplication.UnicodeUTF8))
        self.versionListWidget.item(6).setText(QtGui.QApplication.translate("Form", "v006 (latest)", None, QtGui.QApplication.UnicodeUTF8))
        self.versionListWidget.item(7).setText(QtGui.QApplication.translate("Form", "<latest>", None, QtGui.QApplication.UnicodeUTF8))
        self.versionListWidget.item(8).setText(QtGui.QApplication.translate("Form", "<approved>", None, QtGui.QApplication.UnicodeUTF8))
        self.versionListWidget.setSortingEnabled(__sortingEnabled)

