# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/data/Public/qt-learning/ui/windows/assetBrowser/forms/assetActions.ui'
#
# Created: Tue Nov 14 18:49:57 2017
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(224, 109)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtGui.QFrame(Form)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.copyPasteLayout = QtGui.QHBoxLayout()
        self.copyPasteLayout.setSpacing(3)
        self.copyPasteLayout.setObjectName("copyPasteLayout")
        self.copyToClipboardButton = QtGui.QToolButton(self.frame)
        self.copyToClipboardButton.setObjectName("copyToClipboardButton")
        self.copyPasteLayout.addWidget(self.copyToClipboardButton)
        self.pasteFromClipboardButton = QtGui.QToolButton(self.frame)
        self.pasteFromClipboardButton.setObjectName("pasteFromClipboardButton")
        self.copyPasteLayout.addWidget(self.pasteFromClipboardButton)
        self.verticalLayout_2.addLayout(self.copyPasteLayout)
        self.line_1 = QtGui.QFrame(self.frame)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout_2.addWidget(self.line_1)
        self.openLayout = QtGui.QHBoxLayout()
        self.openLayout.setSpacing(3)
        self.openLayout.setObjectName("openLayout")
        self.openButton = QtGui.QToolButton(self.frame)
        self.openButton.setObjectName("openButton")
        self.openLayout.addWidget(self.openButton)
        self.loadButton = QtGui.QToolButton(self.frame)
        self.loadButton.setObjectName("loadButton")
        self.openLayout.addWidget(self.loadButton)
        self.playButton = QtGui.QToolButton(self.frame)
        self.playButton.setObjectName("playButton")
        self.openLayout.addWidget(self.playButton)
        self.verticalLayout_2.addLayout(self.openLayout)
        self.processLayout = QtGui.QHBoxLayout()
        self.processLayout.setSpacing(3)
        self.processLayout.setObjectName("processLayout")
        self.reviewButton = QtGui.QToolButton(self.frame)
        self.reviewButton.setObjectName("reviewButton")
        self.processLayout.addWidget(self.reviewButton)
        self.sendButton = QtGui.QToolButton(self.frame)
        self.sendButton.setObjectName("sendButton")
        self.processLayout.addWidget(self.sendButton)
        self.approveButton = QtGui.QToolButton(self.frame)
        self.approveButton.setObjectName("approveButton")
        self.processLayout.addWidget(self.approveButton)
        self.verticalLayout_2.addLayout(self.processLayout)
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.deleteLayout = QtGui.QHBoxLayout()
        self.deleteLayout.setSpacing(3)
        self.deleteLayout.setObjectName("deleteLayout")
        self.deleteButton = QtGui.QToolButton(self.frame)
        self.deleteButton.setObjectName("deleteButton")
        self.deleteLayout.addWidget(self.deleteButton)
        self.verticalLayout_2.addLayout(self.deleteLayout)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.copyToClipboardButton.setText(QtGui.QApplication.translate("Form", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.pasteFromClipboardButton.setText(QtGui.QApplication.translate("Form", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setText(QtGui.QApplication.translate("Form", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("Form", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("Form", "Play....", None, QtGui.QApplication.UnicodeUTF8))
        self.reviewButton.setText(QtGui.QApplication.translate("Form", "Review...", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setText(QtGui.QApplication.translate("Form", "Send...", None, QtGui.QApplication.UnicodeUTF8))
        self.approveButton.setText(QtGui.QApplication.translate("Form", "Approve...", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("Form", "Delete...", None, QtGui.QApplication.UnicodeUTF8))

