# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\qt-learning\ui\windows\assetBrowser\forms\searchCustomField.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(890, 161)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_6)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        self.comboBox_7.setObjectName("comboBox_7")
        self.horizontalLayout_2.addWidget(self.comboBox_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_3.addWidget(self.comboBox_3)
        self.comboBox_8 = QtWidgets.QComboBox(Form)
        self.comboBox_8.setObjectName("comboBox_8")
        self.horizontalLayout_3.addWidget(self.comboBox_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_4.addWidget(self.comboBox_4)
        self.comboBox_9 = QtWidgets.QComboBox(Form)
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout_4.addWidget(self.comboBox_9)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_5.addWidget(self.comboBox_5)
        self.comboBox_10 = QtWidgets.QComboBox(Form)
        self.comboBox_10.setObjectName("comboBox_10")
        self.horizontalLayout_5.addWidget(self.comboBox_10)
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "None"))
        self.comboBox.setItemText(1, _translate("Form", "Name"))
        self.comboBox.setItemText(2, _translate("Form", "Type"))
        self.comboBox.setItemText(3, _translate("Form", "Subname"))
        self.comboBox.setItemText(4, _translate("Form", "Instance"))
        self.comboBox.setItemText(5, _translate("Form", "Variant"))
        self.comboBox.setItemText(6, _translate("Form", "Resolution"))
        self.comboBox.setItemText(7, _translate("Form", "Tag"))
        self.comboBox.setItemText(8, _translate("Form", "Path"))
        self.comboBox.setItemText(9, _translate("Form", "Type"))
        self.comboBox.setItemText(10, _translate("Form", "Comment"))
        self.comboBox.setItemText(11, _translate("Form", "Created By User"))
        self.comboBox.setItemText(12, _translate("Form", "Created Date Time"))
        self.comboBox.setItemText(13, _translate("Form", "ID"))
        self.comboBox_6.setItemText(0, _translate("Form", "is equal to"))
        self.comboBox_6.setItemText(1, _translate("Form", "is not equal to"))
        self.comboBox_6.setItemText(2, _translate("Form", "is in"))
        self.comboBox_6.setItemText(3, _translate("Form", "is not in"))
        self.comboBox_6.setItemText(4, _translate("Form", "is greater than"))
        self.comboBox_6.setItemText(5, _translate("Form", "is less than"))
        self.comboBox_6.setItemText(6, _translate("Form", "before"))
        self.comboBox_6.setItemText(7, _translate("Form", "after"))

