# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P:\qt-learning\ui\windows\assetBrowser\forms\searchTagFinder.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1034, 390)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.scrollArea.setFont(font)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1264, 357))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget_11 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_11.sizePolicy().hasHeightForWidth())
        self.listWidget_11.setSizePolicy(sizePolicy)
        self.listWidget_11.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.listWidget_11.setFont(font)
        self.listWidget_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_11.setObjectName("listWidget_11")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_11.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_11.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_11)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget_9 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_9.sizePolicy().hasHeightForWidth())
        self.listWidget_9.setSizePolicy(sizePolicy)
        self.listWidget_9.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.listWidget_9.setFont(font)
        self.listWidget_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_9.setAutoScroll(True)
        self.listWidget_9.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_9.setMovement(QtWidgets.QListView.Static)
        self.listWidget_9.setObjectName("listWidget_9")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_9.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_9.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_9.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_9.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_9.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget_9)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.listWidget_10 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget_10.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.listWidget_10.setFont(font)
        self.listWidget_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_10.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_10.setObjectName("listWidget_10")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_10.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_10.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_10.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_10.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_10.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_10.addItem(item)
        self.verticalLayout_3.addWidget(self.listWidget_10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.listWidget_13 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget_13.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.listWidget_13.setFont(font)
        self.listWidget_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_13.setObjectName("listWidget_13")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_13.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_13.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_13.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_13.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_13.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_13.addItem(item)
        self.verticalLayout_4.addWidget(self.listWidget_13)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.listWidget_3 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.listWidget_3.setFont(font)
        self.listWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.verticalLayout_5.addWidget(self.listWidget_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.listWidget.setFont(font)
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_6.addWidget(self.listWidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.listWidget_8 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget_8.setMinimumSize(QtCore.QSize(120, 0))
        self.listWidget_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget_8.setLineWidth(1)
        self.listWidget_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_8.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_8.setMovement(QtWidgets.QListView.Static)
        self.listWidget_8.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_8.setProperty("isWrapping", False)
        self.listWidget_8.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_8.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget_8.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_8.setUniformItemSizes(False)
        self.listWidget_8.setWordWrap(False)
        self.listWidget_8.setSelectionRectVisible(False)
        self.listWidget_8.setObjectName("listWidget_8")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        self.verticalLayout_7.addWidget(self.listWidget_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.listWidget_2 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget_2.setMinimumSize(QtCore.QSize(120, 0))
        self.listWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_8.addWidget(self.listWidget_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.listWidget_4 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_4.sizePolicy().hasHeightForWidth())
        self.listWidget_4.setSizePolicy(sizePolicy)
        self.listWidget_4.setMinimumSize(QtCore.QSize(120, 0))
        self.listWidget_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_4.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_4.setObjectName("listWidget_4")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        self.verticalLayout_9.addWidget(self.listWidget_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.listWidget_5 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_5.sizePolicy().hasHeightForWidth())
        self.listWidget_5.setSizePolicy(sizePolicy)
        self.listWidget_5.setMinimumSize(QtCore.QSize(120, 0))
        self.listWidget_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_5.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_5.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget_5.setObjectName("listWidget_5")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_5.addItem(item)
        self.verticalLayout_10.addWidget(self.listWidget_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Project"))
        __sortingEnabled = self.listWidget_11.isSortingEnabled()
        self.listWidget_11.setSortingEnabled(False)
        item = self.listWidget_11.item(0)
        item.setText(_translate("Form", "project"))
        item = self.listWidget_11.item(1)
        item.setText(_translate("Form", "project 2"))
        self.listWidget_11.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Form", "Sequence"))
        __sortingEnabled = self.listWidget_9.isSortingEnabled()
        self.listWidget_9.setSortingEnabled(False)
        item = self.listWidget_9.item(0)
        item.setText(_translate("Form", "sequence"))
        item = self.listWidget_9.item(1)
        item.setText(_translate("Form", "sh"))
        item = self.listWidget_9.item(2)
        item.setText(_translate("Form", "br"))
        item = self.listWidget_9.item(3)
        item.setText(_translate("Form", "pw"))
        item = self.listWidget_9.item(4)
        item.setText(_translate("Form", "if"))
        self.listWidget_9.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("Form", "Shot"))
        __sortingEnabled = self.listWidget_10.isSortingEnabled()
        self.listWidget_10.setSortingEnabled(False)
        item = self.listWidget_10.item(0)
        item.setText(_translate("Form", "sh-0010"))
        item = self.listWidget_10.item(1)
        item.setText(_translate("Form", "sh-0020"))
        item = self.listWidget_10.item(2)
        item.setText(_translate("Form", "sh-0030"))
        item = self.listWidget_10.item(3)
        item.setText(_translate("Form", "sh-0040"))
        item = self.listWidget_10.item(4)
        item.setText(_translate("Form", "sh-0050"))
        item = self.listWidget_10.item(5)
        item.setText(_translate("Form", "sh-0060"))
        self.listWidget_10.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("Form", "User"))
        __sortingEnabled = self.listWidget_13.isSortingEnabled()
        self.listWidget_13.setSortingEnabled(False)
        item = self.listWidget_13.item(0)
        item.setText(_translate("Form", "<all users>"))
        item = self.listWidget_13.item(1)
        item.setText(_translate("Form", "<current user>"))
        item = self.listWidget_13.item(2)
        item.setText(_translate("Form", "bob"))
        item = self.listWidget_13.item(3)
        item.setText(_translate("Form", "jane"))
        item = self.listWidget_13.item(4)
        item.setText(_translate("Form", "john"))
        item = self.listWidget_13.item(5)
        item.setText(_translate("Form", "sam"))
        self.listWidget_13.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("Form", "Name"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("Form", "Name 1"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("Form", "Name 2"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("Form", "Name 3"))
        item = self.listWidget_3.item(3)
        item.setText(_translate("Form", "Name 4"))
        item = self.listWidget_3.item(4)
        item.setText(_translate("Form", "Name 5"))
        item = self.listWidget_3.item(5)
        item.setText(_translate("Form", "Name 6"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("Form", "Subname"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "null"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "Subname 1"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "Subname 2"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "Subname 3"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "Subname 4"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("Form", "Type"))
        self.listWidget_8.setSortingEnabled(False)
        __sortingEnabled = self.listWidget_8.isSortingEnabled()
        self.listWidget_8.setSortingEnabled(False)
        item = self.listWidget_8.item(0)
        item.setText(_translate("Form", "Rig"))
        item = self.listWidget_8.item(1)
        item.setText(_translate("Form", "Lens"))
        item = self.listWidget_8.item(2)
        item.setText(_translate("Form", "Media"))
        item = self.listWidget_8.item(3)
        item.setText(_translate("Form", "Audio"))
        item = self.listWidget_8.item(4)
        item.setText(_translate("Form", "Shader"))
        item = self.listWidget_8.item(5)
        item.setText(_translate("Form", "WorkFile"))
        item = self.listWidget_8.item(6)
        item.setText(_translate("Form", "Cache"))
        item = self.listWidget_8.item(7)
        item.setText(_translate("Form", "Model"))
        item = self.listWidget_8.item(8)
        item.setText(_translate("Form", "ImageSequence"))
        item = self.listWidget_8.item(9)
        item.setText(_translate("Form", "Texture"))
        item = self.listWidget_8.item(10)
        item.setText(_translate("Form", "Animation"))
        item = self.listWidget_8.item(11)
        item.setText(_translate("Form", "Camera"))
        self.listWidget_8.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("Form", "Variant"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("Form", "null"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("Form", "Variant 1"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("Form", "Variant 2"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("Form", "Variant 3"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("Form", "Resolution"))
        __sortingEnabled = self.listWidget_4.isSortingEnabled()
        self.listWidget_4.setSortingEnabled(False)
        item = self.listWidget_4.item(0)
        item.setText(_translate("Form", "null"))
        item = self.listWidget_4.item(1)
        item.setText(_translate("Form", "Resolution 1"))
        item = self.listWidget_4.item(2)
        item.setText(_translate("Form", "Resolution 2"))
        item = self.listWidget_4.item(3)
        item.setText(_translate("Form", "Resolution 3"))
        item = self.listWidget_4.item(4)
        item.setText(_translate("Form", "Resolution 4"))
        item = self.listWidget_4.item(5)
        item.setText(_translate("Form", "Resolution 5"))
        self.listWidget_4.setSortingEnabled(__sortingEnabled)
        self.label_10.setText(_translate("Form", "Version"))
        __sortingEnabled = self.listWidget_5.isSortingEnabled()
        self.listWidget_5.setSortingEnabled(False)
        item = self.listWidget_5.item(0)
        item.setText(_translate("Form", "all versions"))
        item = self.listWidget_5.item(1)
        item.setText(_translate("Form", "online versions"))
        item = self.listWidget_5.item(2)
        item.setText(_translate("Form", "deleted versions"))
        item = self.listWidget_5.item(3)
        item.setText(_translate("Form", "latest version"))
        item = self.listWidget_5.item(4)
        item.setText(_translate("Form", "approved versions"))
        self.listWidget_5.setSortingEnabled(__sortingEnabled)

